services:
  txns_query:
    build: 
      dockerfile: Dockerfile.txns_query
    volumes:
      - ./data/:/workspace/data/
  swagger:
    build: 
      dockerfile: Dockerfile.swagger
    volumes:
      - ./data/:/workspace/data/
    ports:
      - "8080:8080"