# syntax=docker/dockerfile:1
FROM python:3.8-bullseye
WORKDIR /workspace
RUN apt-get update
RUN apt-get install -y --no-install-recommends make automake gcc g++ subversion python3-dev musl-dev 
COPY . .
RUN pip install -r requirements.txt
EXPOSE 8080
ENV DBPATH=/workspace/data/db.db
WORKDIR /workspace/api/server
CMD ["timeout", "2m", "python", "-m", "swagger_server"]

# COPY requirements.txt requirements.txt
# ENV FLASK_APP=app.py
# ENV FLASK_RUN_HOST=0.0.0.0
# EXPOSE 5000